# Generated by Django 5.2.5 on 2025-08-08 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CountryMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('gdp_ppp_per_capita', models.FloatField(blank=True, null=True)),
                ('life_expectancy', models.FloatField(blank=True, null=True)),
                ('education_index', models.FloatField(blank=True, null=True)),
                ('safety_index', models.FloatField(blank=True, null=True)),
                ('prosperity_index', models.FloatField(blank=True, null=True)),
                ('freedom_of_speech_index', models.FloatField(blank=True, null=True)),
                ('democracy_index', models.FloatField(blank=True, null=True)),
                ('corruption_index', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='countries.country')),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'year'], name='idx_country_year')],
                'constraints': [models.UniqueConstraint(fields=('country', 'year'), name='uniq_country_year')],
            },
        ),
    ]
